# Generated by Django 4.2.11 on 2024-04-04 21:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='joe_product_name_20b806_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'status', 'Affiliate_link', 'meta_description', 'category', 'content'], name='joe_product_name_e6642b_idx'),
        ),
    ]
