"""
Django settings for jinjo project.

Generated by 'django-admin startproject' using Django 3.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from decouple import config
# from redislite import StrictRedis
 
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = config('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = config('DEBUG', default=True, cast=bool)
ALLOWED_HOSTS = ['https://www.kemisto.com', 'www.kemisto.com', 'kemisto.com']
 

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'joe.apps.JoeConfig',
    
    'django_social_share',
    'crispy_forms',
    'crispy_bootstrap4',
    
    'ckeditor',
    'ckeditor_uploader', 
    'compressor',
    
]

SITE_ID = 1

CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"


MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware', 
    
    'django.middleware.security.SecurityMiddleware',
    'csp.contrib.rate_limiting.RateLimitedCSPMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]



ROOT_URLCONF = 'jinjo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'csp.context_processors.nonce'
            ],
        },
    },
]

WSGI_APPLICATION = 'jinjo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': 'localhost',
        'PORT': config('DB_PORT'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'", 
            'charset': 'utf8mb4',
            'use_unicode': True,
        }
    }
}



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR,  "staticfiles")
]

STATIC_ROOT = '/home/kemisto/Kemisto/kikabu/static/' 

  
MEDIA_URL = '/media/'
MEDIA_ROOT = '/home/kemisto/Kemisto/kikabu/media/'
 

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',

    # Add this
    'compressor.finders.CompressorFinder',
)


COMPRESS_ENABLED = not DEBUG
COMPRESS_CSS_HASHING_METHOD = 'content'
COMPRESS_FILTERS = {
    'css':[
        'compressor.filters.css_default.CssAbsoluteFilter',
        'compressor.filters.cssmin.rCSSMinFilter',
    ],
    'js':[
        'compressor.filters.jsmin.JSMinFilter',
    ]
}
HTML_MINIFY = True
KEEP_COMMENTS_ON_MINIFYING = True

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'joe.User'

LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'home'

CONTENT_TYPES = ['image', 'video']
MAX_UPLOAD_SIZE = "10485760"



ENCRYPT_KEY = b'hoxL0Bjo46h6Eal3QxoY-vAcnr4B_8ANOggRDAaguWk='
HASHIDS_SALT = 'h1xL0Bjo'


SECURE_HSTS_SECONDS = 315360000000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_SSL_REDIRECT = True
SECURE_CONTENT_TYPE_NOSNIFF = True
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'strict'
SESSION_COOKIE_SECURE = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = "strict-origin"



CSP_MEDIA_SRC = ["* blob:",]

CSP_REPORT_URI = ["'self'"]

CSP_DEFAULT_SRC = ["'self' 'unsafe-inline' 'unsafe-eval' data: gap: content:",
"https://www.google-analytics.com 'unsafe-inline' 'unsafe-eval' data: gap: content:",
"https://pagead2.googlesyndication.com 'unsafe-inline' 'unsafe-eval' data: gap: content:",
"https://googleads.g.doubleclick.net 'unsafe-inline' 'unsafe-eval' data: gap: content:",
"https://www.google.com 'unsafe-inline' 'unsafe-eval' data: gap: content:",
"https://www.gstatic.com 'unsafe-inline' 'unsafe-eval' data: gap: content:",
"https://securepubads.g.doubleclick.net 'unsafe-inline' 'unsafe-eval' data: gap: content:",
"https://cdn.jsdelivr.net 'unsafe-inline' 'unsafe-eval'",
"https://tpc.googlesyndication.com 'unsafe-inline' 'unsafe-eval'",
"https://pl21949916.toprevenuegate.com 'unsafe-inline' 'unsafe-eval'",
"https://pl19112863.toprevenuegate.com 'unsafe-inline' 'unsafe-eval'",
]

# 'unsafe-inline' 'unsafe-hashes'

# style from our domain and bootstrapcdn
CSP_STYLE_SRC = ["'self' 'unsafe-inline' 'unsafe-eval'",
    "https://stackpath.bootstrapcdn.com 'unsafe-inline' 'unsafe-eval'",
    "https://maxcdn.bootstrapcdn.com 'unsafe-inline' 'unsafe-eval'",
    "https://cdn.jsdelivr.net 'unsafe-inline' 'unsafe-eval'",
    "https://code.jquery.com 'unsafe-inline' 'unsafe-eval'",
    "https://use.fontawesome.com 'unsafe-inline' 'unsafe-eval'",
    "https://cdnjs.cloudflare.com",
    "https://maxcdn.bootstrapcdn.com ",
    "https://unpkg.com/"
    ]

# scripts from our domain and other domains
CSP_SCRIPT_SRC = ["'self' 'unsafe-inline' 'unsafe-eval'",
    "https://cdn.jsdelivr.net/npm",
    "https://stackpath.bootstrapcdn.com",
    "https://code.jquery.com ",
    "https://ajax.cloudflare.com ",
    "https://ajax.googleapis.com ",
    "https://code.jquery.com ",
    "https://cdnjs.cloudflare.com",
    "https://maxcdn.bootstrapcdn.com ",
    "https://www.googletagmanager.com ",
    "https://unpkg.com/",
    "https://assets.pinterest.com/js/pinit.js",
    "https://use.fontawesome.com 'unsafe-inline' 'unsafe-eval'",
    "https://www.google-analytics.com",
    "https://pagead2.googlesyndication.com 'unsafe-inline' 'unsafe-eval'", 
    "https://googleads.g.doubleclick.net 'unsafe-inline' 'unsafe-eval'",
    "https://www.google.com 'unsafe-inline' 'unsafe-eval'",
    "https://www.gstatic.com 'unsafe-inline' 'unsafe-eval'",
    "https://securepubads.g.doubleclick.net 'unsafe-inline' 'unsafe-eval'",
    "https://cdn.jsdelivr.net 'unsafe-inline' 'unsafe-eval'",
    "https://tpc.googlesyndication.com 'unsafe-inline' 'unsafe-eval'",
    "https://pl21949916.toprevenuegate.com 'unsafe-inline' 'unsafe-eval'",
    "https://pl19112863.toprevenuegate.com 'unsafe-inline' 'unsafe-eval'",
    # "https://adservice.google.com",
    # "https://adservice.google.com.ng",
    # "https://tpc.googlesyndication.com",
    # "https://partner.googleadservices.com",
    # "https://pl19112863.highrevenuegate.com",
    ]

# images from our domain and other domains
CSP_IMG_SRC = ["* blob: data:;",]

# loading manifest, workers, frames, etc
CSP_FONT_SRC = ["'self'",
                "https://use.fontawesome.com 'unsafe-inline'",
                "https://cdnjs.cloudflare.com",
                "https://cdn.jsdelivr.net ",
                "https://www.google.com",
                "https://www.gstatic.com",
                "https://pagead2.googlesyndication.com",
                ]
CSP_CONNECT_SRC = ["'self'",
    "https://www.google-analytics.com",
    "https://www.googletagmanager.com",
    "https://assets.pinterest.com",
    "https://www.google.com",
    "https://www.gstatic.com",
    "https://www.googletagmanager.com",
    "https://pagead2.googlesyndication.com",
    "https://googleads.g.doubleclick.net/"
    "https://cdn.jsdelivr.net",
    "https://tpc.googlesyndication.com",
    "https://securepubads.g.doubleclick.net",
    "https://pl21949916.toprevenuegate.com",
    "https://pl19112863.toprevenuegate.com",
    ]
CSP_OBJECT_SRC = ["'self'", ]
CSP_BASE_URI = ["'self'", ]
CSP_FRAME_ANCESTORS = ["'self'",
                        "https://pagead2.googlesyndication.com",
                        "https://assets.pinterest.com/js/pinit.js",
                        "https://googleads.g.doubleclick.net/",
                        "https://securepubads.g.doubleclick.net",
                        "https://pl21949916.toprevenuegate.com",
                        "https://pl19112863.toprevenuegate.com",
                    ]
CSP_FORM_ACTION = ["'self'", ]
CSP_INCLUDE_NONCE_IN = ['script-src', ]
CSP_MANIFEST_SRC = ["'self'", ]
CSP_WORKER_SRC = ["'self'", ]


CSP_UPGRADE_INSECURE_REQUESTS = not DEBUG
CSP_REPORT_PERCENTAGE = 0.6

